name: flutter_weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  http: ^1.1.0
  provider: ^6.0.5
  location: ^5.0.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
